version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
      - "8000:8000" # Porta para o DynamoDB
    volumes:
      - localstack_data:/localstack
volumes:
  localstack_data: